name: Upload to code from current directory to other repo

on:
  push:
    branches: 
      - master

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: List directory
      run: pwd
    
