name: Upload to code from current directory to other repo

on:
  push:
    branches: 
      - master

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: List directory
      run: ls
    - name: Git config
      run: |
        git config --global user.email ${{secrets.EMAIL}}
        git config --global user.name ${{secrets.NAME}}
    - name: Git add
      run: |
        cd Scripts/Preds
        git add .
        git status
    - name: Git push
      run: |
        git remote add diff_remote ${{secrets.REMOTE_URL}}
        git push diff_remote master
      # env: 
      #   LS: ${{secrets.COMMAND}}
      # run: $LS