name: Upload to code from current directory to other repo

on:
  push:
    branches: 
      - master

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: List directory
      run: ls
      # env: 
      #   LS: ${{secrets.COMMAND}}
      # run: $LS