name: Upload to code from current directory to other repo

on:
  push:
    branches: 
      - master

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: List directory
      run: ls
    - name: push to repo
    - run: |
          git add hello.py
          git commit -m "PUSH"
          git push https://github.com/Balkongen/App.git
