name: Push other repo

on:
  push:
    branches: 
      - master

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: Scripts/Preds
    - name: List
      run: ls