name: Push other repo

on:
  push:
    branches: 
      - master

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Checkout other repo
      uses: actions/checkout@v4
      with:
        repository: ${{secrets.REPOSITORY}}
        token: ${{secrets.TOKEN}}
        persist-credentials: true
    
    - name: ls directory
      run: ls