name: Push other repo

on:
  push:
    branches: 
      - master

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: List
      run: ls
        
    # - name: navigate TO folder
    #   run: cd Scripts/Preds
    - name: Clone
      run: git clone ${{secrets.REMOTE_URL_WITH_TOKEN}} diff_repo 
    # - name: git status
    #   run: git status
    # - name: git branches
    #   run: git branch -v
    # - name: git remote
    #   run: git remote -v
    - name: Remove files in directory
      run: rm diff_repo/preds/*
    - name: COPY directory
      run: cp -r Scripts/Preds/* diff_repo/preds
    # - name: list files in this
    #   run: ls Scripts
    # - name: list files in other
    #   run: ls diff_repo/preds
    # - name: ls in diff_repo
    #   run: ls diff_repo
    # - name: pwd
    #   run: pwd
    - name: check diff_repo
      run: |
        cd diff_repo
        git config --global user.email ${{secrets.EMAIL}}
        git config --global user.name ${{secrets.NAME}}
        git remote add diff_repo_origin ${{secrets.REMOTE_URL}}
        git add -A
        git commit -m "Updated models"
        git push diff_repo_origin
    # - name: check root
    #   run: |
    #     ls
    #     git remote -v
      # git push diff_repo_origin
    
    
    # - name: git push
    #   run: |
    #     git add -A
    #     git commit -m "Updated models"
    #     git push diff_repo_origin
      # TODO push to diff_repo