name: Push other repo

on:
  push:
    branches: 
      - master

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        path: src
        persist-credentials: false

    - name: Checkout other repo
      uses: actions/checkout@v4
      with:
        path: dest
        repository: ${{secrets.REPOSITORY}}
        token: ${{secrets.TOKEN}}
        persist-credentials: true
    
    - name: ls directory
      run: ls

    - name: Remove files in directory
      run: rm dest/preds/* 

    - name: Copy directory
      run: cp -r src/Scripts/Preds/* dest/preds

    - name: git 
      working-directory: dest
      run: |
        git remote -v
        git status